import { InkwellIcon } from "@/entities/tags/type";
import {
  BookOpen,
  Pencil,
  Paintbrush,
  Palette,
  Users,
  Smile,
  Apple,
  Calendar,
  Camera,
  Video,
  MessageCircle,
  Image,
  List,
  CheckCircle,
  Heart,
  Star,
  Globe,
  Clipboard,
  Bell,
  FileText,
} from "lucide-react";

export const iconComponents = {
  [InkwellIcon.BookOpen]: BookOpen,
  [InkwellIcon.Pencil]: Pencil,
  [InkwellIcon.PaintBrush]: Paintbrush,
  [InkwellIcon.Palette]: Palette,
  [InkwellIcon.Users]: Users,
  [InkwellIcon.Smile]: Smile,
  [InkwellIcon.Apple]: Apple,
  [InkwellIcon.Calendar]: Calendar,
  [InkwellIcon.Camera]: Camera,
  [InkwellIcon.Video]: Video,
  [InkwellIcon.MessageCircle]: MessageCircle,
  [InkwellIcon.Image]: Image,
  [InkwellIcon.List]: List,
  [InkwellIcon.CheckCircle]: CheckCircle,
  [InkwellIcon.Heart]: Heart,
  [InkwellIcon.Star]: Star,
  [InkwellIcon.Globe]: Globe,
  [InkwellIcon.Clipboard]: Clipboard,
  [InkwellIcon.Bell]: Bell,
  [InkwellIcon.FileText]: FileText,
};
